create nettoInsults
victormamede/bruno-bot pull request #1
Opened 2023-07-15 03:44 UTC by brunosantoos

2023-07-18 17:16 UTC, victormamede requested changes
fazer alterações pontuadas

2023-07-18 17:16 UTC, victormamede commented on src/main.ts
> +  if (msg.from === groupId) {
Guard do grupo deve estar no começo da função e retornar se o groupId for diferente

2023-07-18 17:16 UTC, victormamede commented on src/main.ts
> +      if (msg.from !== groupId) {
redundante

2023-07-18 17:16 UTC, victormamede commented on src/main.ts
> +const nettoInsults = [
mover isso para arquivo separado

2023-07-18 17:16 UTC, victormamede commented on src/main.ts
> +import { Client, LocalAuth } from 'whatsapp-web.js';
manter formatação com aspas duplas

2023-07-19 11:40 UTC, brunosantoos commented
fazer as alterações.

2023-07-20 18:18 UTC, closed without merging